### PR TITLE
Test whether nodes were mapped by matcher (rather than the edit script generator).

### PR DESCRIPTION
**Pull request by snim2**
This fixes a bug that was introduced in #52

### CODE REVIEW

**Comment by ltratt** [comment]
This doesn't look blocked? I think I can merge it...

**Comment by snim2** [comment]
I think when #53 is merged there will be a merge-conflict with this PR, but I could be wrong!

**Comment by snim2** [comment]
Bringing this up to date with master...

**Comment by snim2** [comment]
Done...

**Comment by ltratt** [comment]
Tests are failing :/

**Comment by snim2** [comment]
OK to squash?

**Comment by ltratt** [comment]
Yep, please squash.

**Comment by snim2** [comment]
Squashed.

**Pull request merged**
