### PR TITLE
Fix serde versions.

### PR DESCRIPTION
**Pull request by snim2**
These versions are chosen to work with the snapshot of rust we
need to use.

### CODE REVIEW

**Comment by ltratt** [comment]
I can confirm this fixes the compilation problems. I wouldn't have thought of this, so well done!

**Comment by snim2** [comment]
Hang about though -- the tests fail! I think that's because of the latest changes in lrlex, I'll try to fix in this PR.

**Comment by ltratt** [comment]
All passing -- merge as-is?

**Comment by snim2** [comment]
Yes please!

**Pull request merged**
