### PR TITLE
Edge cover solver. Finished Stage 3.

### PR DESCRIPTION
**Pull request by k1502606**
Finish minimal edge cover solver which will implement actions to make the from_arena the same as the to_arena. 
- There are test that checks whether the edge scripts actually work or not.
- Next stage is display the changes need to made. 

Please let me know if there are any changes needed to be made. 
Thanks.

### CODE REVIEW

**Comment by ltratt** [comment]
So before I can review this, we need, I think, to rebase this against master. For example, I'm pretty sure the 4 commits from Sarah shouldn't show up at all. Are you OK with doing that?

**Comment by k1502606** [comment]
Ready to re-review.

**Comment by ltratt** [comment]
Why are the last two commits something to do with rebasing? 9bd20320c585631b47367b9b496c54ddd927214c looks like it's Sarah's commit sort-of?

**Comment by k1502606** [comment]
Should I get rid of the rebase commit ? 9bd2032 is the test I made to check if it works. Then it will be integrated in the test section in the file.

**Comment by k1502606** [comment]
Ready for Re-Re-Review

**Comment by ltratt** [comment]
Next question :) https://github.com/softdevteam/diffract/pull/84/commits/fadc18109da5b31d150b97fa7bd3b260fc6d49eb suggests it's 19 days old. Is it new code or ...?

**Comment by ltratt** [comment]
Also notice that GitHub now says this is out of date with master. Did you do `rebase -i origin/master`?

**Comment by k1502606** [comment]
I haven't done rebase -i origin master.  fadc181 I usually update the code, I was old code. Should I update branch ?

**Comment by ltratt** [comment]
Ah, so I think that might be the root of the confusion. In nearly all circumstances "please rebase" means `rebase -i origin/master`. If you can, I suggest you do `git reset --hard <the original last commit you pushed to this branch>` and then go forwards from there.

**Pull request closed without merging**
