### PR TITLE
tool_lints is now stable.

### PR DESCRIPTION
**Pull request by snim2**

### CODE REVIEW

**Comment by snim2** [comment]
Ah, upstream changes in grmtools, I think?

```rust
error[E0432]: unresolved import `lrlex::Lexer`                                                                                                                                      
  --> src/lib/parser.rs:47:24                                                                                                                                                       
   |                                                                                                                                                                                
47 | use lrlex::{build_lex, Lexer};                                                                                                                                                 
   |                        ^^^^^ no `Lexer` in the root. Did you mean to use `lexer`?                                                                                              
                                                                                                                                                                                    
error[E0425]: cannot find function `parse` in module `parser`                                                                                                                       
   --> src/lib/parser.rs:156:17                                                                                                                                                     
    |                                                                                                                                                                               
156 |         parser::parse(&grm, &sgraph, &stable, &lexemes).map_err(|_| {                                                                                                         
    |                 ^^^^^ not found in `parser`                                                                                                                                   
help: possible candidate is found in another module, you can import it into scope                                                                                                   
    |                                                                                                                                                                               
40  | use term::terminfo::parser::compiled::parse;                                                                                                                                  
    |                                                                                                                                                                               
                                                                                                                                                                                    
error[E0599]: no method named `lexemes` found for type `impl lrpar::Lexer<u16>` in the current scope                                                                                
   --> src/lib/parser.rs:151:25                                                                                                                                                     
    |                                                                                                                                                                               
151 |     let lexemes = lexer.lexemes()                                                                                                                                             
    |                         ^^^^^^^                                                                                                                                               
 ```

**Comment by ltratt** [comment]
Yep. I'll push a PR to fix things tomorrow.

**Comment by snim2** [comment]
Many thanks.

**Comment by snim2** [comment]
Updating to pull in latest merges in master...

**Review by ltratt — APPROVED** [review]

**Pull request merged**
