### PR TITLE
Code improvements suggested by clippy and rustfmt.

### PR DESCRIPTION
**Pull request by snim2**
This should have gone in the last PR. Mea maxima culpa.

### CODE REVIEW

**Comment by ltratt** [comment]
Given that the `type`s are only used in one place, does moving them help? It just seems to add a useless level of indirection to me TBH...

**Comment by snim2** [comment]
I don't object to having them as `type`s but I agree, it's not the most useful.

**Comment by ltratt** [comment]
I'd suggest we back that bit back out then -- a smaller diff is no bad thing ;)

**Comment by snim2** [comment]
Needs squashing

**Comment by ltratt** [comment]
Yep, please squash.

**Comment by snim2** [comment]
Squashed

**Pull request merged**
