### PR TITLE
Add comments to Java grammar.

### PR DESCRIPTION
**Pull request by snim2**
Example test case:

```java
/* Multiline 1 */
public /* Multiline 2 */ class /* Multiline 3 */ Comment /* Multiline 4 */ {
    // Single line comment.
} /* Multiline 5
   *
   *
   *
   */
```

Parser output:

comment

### CODE REVIEW

**Comment by ltratt** [comment]
Does this deal with nested `/* ... */` comments properly? I'm not sure what Java's rules on that are to be honest...

**Comment by snim2** [comment]
Good question, let me check...

**Comment by snim2** [comment]
`javac` gives me all kinds of errors if I nest multiline comments:

```
$ javac tests/NestedComment.java 
tests/NestedComment.java:7: error: class, interface, or enum expected
 * /*  /* Commentception. */ */
                             ^
1 error
```

but I have added a test case for a single line comment nested within a multiline one.

This branch now needs squashing.

**Comment by ltratt** [comment]
Looks good to me. If you squash, I can merge.

**Comment by snim2** [comment]
Thanks, squashed!

**Pull request merged**
